### PR TITLE
Add node-oracledb and create an example endpoint we can use for testing

### PR DESCRIPTION
**Pull request by mjoyce91**

### CODE REVIEW

**Review by scott062 — COMMENTED** [review]
Screen Shot 2021-02-04 at 7 31 33 AM

How'd you run this with the API to test it? I ran it with `local-mock`

I'm guessing its just the different compose files when running the API and how the mock references it?

**Comment by mjoyce91** [comment]
@scott062 I always use `docker-compose-api-only.yml`

**Comment by scott062** [comment]
This works but just need to note that you need to run api-only when doing it

**Review by scott062 — APPROVED** [review]
👍

**Pull request merged**
