### PR TITLE
Feature/unit testing

### PR DESCRIPTION
**Pull request by rtirserio**
Unit testing for mock. Starting with verifying the shape of the data returned as that seems to be the most common issue we see when mocking FSBid services. Can be run with `docker-compose run app npm test`. More tests to come

### CODE REVIEW

**Comment by mjoyce91** [comment]
Should we add to CircleCI?

**Comment by burgwyn** [comment]
You want to try GitHub Actions?

**Comment by rtirserio** [comment]
I thought about getting this into GitHub actions to give it a try. I can do that as a different PR, for these tests I wanted to be sure i had a way to verify the response shape when im changing things

**Comment by rtirserio** [comment]
I added a github action to run the tests. It works on the master branch (no tests there but it does what would be expected)

**Pull request merged**
