### PR TITLE
chore: sort the skills collection on the employee when fetched

### PR DESCRIPTION
**Pull request by rtirserio**
sorts the employees skills alphabetically when fetched

### CODE REVIEW

**Comment by mjoyce91** [comment]
Only somewhat related, but the value to sort by skill should be `per_skill_code`, but this returns `error: column "per_skill_code" does not exist` from the mock.

**Comment by rtirserio** [comment]
> per_skill_code

thats the name of the param passed?

**Comment by mjoyce91** [comment]
@rtirserio yes. I think that also means we would want to change the sorting here to use the code, not the description. They do not allow sorting by the description.

**Comment by rtirserio** [comment]
@mjoyce91 - fixed

**Pull request merged**
