### PR TITLE
Add unaccompanied status model and associate with locations

### PR DESCRIPTION
**Pull request by mjoyce91**
Be sure to migrate and re-seed

### CODE REVIEW

**Comment by scott062** [comment]
Probably not intended, but do we want `us_code` to be returned by `/locations`? 

FSBid `/postAttributes` returns some additional params of:

`us_create_id`
`us_create_date`
`us_update_id`
`us_update_date`

Should we add these as blank fields to the unaccompanied table reference data? 

General Question: We want `us_code` filter for all AP/PV/Tandem ideally (even though it may not exist yet in FSBid)?

**Comment by mjoyce91** [comment]
Go to bed

**Comment by mjoyce91** [comment]
@scott062 

> Probably not intended, but do we want us_code to be returned by /locations?

Let me check to see if that actually gets returned

> FSBid /postAttributes returns some additional params of:
us_create_id
us_create_date
us_update_id
us_update_date
Should we add these as blank fields to the unaccompanied table reference data?

I excluded them because they're not used and I can't think of anything we'd need to use them for

> General Question: We want us_code filter for all AP/PV/Tandem ideally (even though it may not exist yet in FSBid)?

Yeah, whether or not it's available yet, I'm going to leave it there for all of them. I don't think we'll want to push this functionality until its available in all search types. My next step is to wrap it in a feature flag, so that we can flip it on when its ready.

**Comment by mjoyce91** [comment]
@scott062 

> Probably not intended, but do we want us_code to be returned by /locations?

They do not return unaccompanied data in the /locations endpoint

**Pull request merged**
