### PR TITLE
new generic v2/positions route

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**
Dual Merge: 
- [FE PR ](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2246)
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/700)

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
Back in WIP to update EP from WS call

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
@scott062 thanks for catching that the previous one was the wrong EP

**Review by scott062 — APPROVED** [review]
🔍

**Comment by scott062** [comment]
TO-DO: Add more search functionality outside of pos_num_txt (no use-cases yet so this can wait)

**Pull request merged**
