### PR TITLE
Force query params for availablebidders endpoints

### PR DESCRIPTION
**Pull request by mjoyce91**
Match FSBID with required parameters

### CODE REVIEW

**Review by elizabeth-jimenez — CHANGES_REQUESTED** [review]
Not so much changes as a question. In Azure, leaving out `order_by` is still returning results. `is_asc` is a dropd, so not sure how to test not sending that along.

**Comment by scott062** [comment]
@elizabeth-jimenez they probably have a default sort. Instead of erroring without a sort, we could just default it @mjoyce91

**Comment by mjoyce91** [comment]
@elizabeth-jimenez @scott062 - updated

**Review by elizabeth-jimenez — APPROVED** [review]
👍

**Pull request merged**
