### PR TITLE
Add the ability to get an Agent by passing the client's perdet

### PR DESCRIPTION
**Pull request by mjoyce91**

### CODE REVIEW

**Comment by scott062** [comment]
@mjoyce91 Need to import lodash

**Comment by mjoyce91** [comment]
good catch @scott062

**Comment by scott062** [comment]
Just to clarify - passing the perdet to the appropriate agents endpoint is pointing to the CLIENT's perdet - NOT AGENT's. And we look up agents by HRU_ID - NOT PERDET?

**Comment by mjoyce91** [comment]
@scott062 - yep exactly

**Pull request merged**
